# Generated by Django 4.1.7 on 2023-05-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, db_column='Ano', max_length=255, null=True)),
                ('datainicio', models.DateField(blank=True, db_column='DataInicio', null=True)),
                ('datafim', models.DateField(blank=True, db_column='DataFim', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AnoLetivo',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('curso', models.CharField(blank=True, db_column='curso', max_length=255, null=True)),
                ('codigo', models.IntegerField(blank=True, db_column='Codigo', null=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(db_column='ID2', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('estado', models.TextField(db_column='Estado')),
                ('codigodisciplina', models.IntegerField(blank=True, db_column='codigodisciplina', null=True)),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('codigo', models.IntegerField(blank=True, db_column='Codigo', default=0, primary_key=True, serialize=False)),
                ('ativo', models.CharField(blank=True, db_column='Ativo', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('individuo', models.CharField(blank=True, db_column='Individuo', max_length=255, null=True)),
                ('data_de_nascimento', models.CharField(blank=True, db_column='data_de_nascimento', max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, db_column='sexo', max_length=255, null=True)),
                ('tipo_de_identificacao', models.CharField(blank=True, db_column='tipo_de_Identificacao', max_length=255, null=True)),
                ('identificacao', models.CharField(blank=True, db_column='identificacao', max_length=255, null=True)),
                ('data_de_emissao_de_idenficacao', models.CharField(blank=True, db_column='data_de_emissao_de_idenficacao', max_length=255, null=True)),
                ('nacionalidade', models.CharField(blank=True, db_column='nacionalidade', max_length=255, null=True)),
                ('arquivo', models.CharField(blank=True, db_column='arquivo', max_length=255, null=True)),
                ('data_de_validade_da_identificacao', models.CharField(blank=True, db_column='data_de_validade_da_identificacao', max_length=255, null=True)),
                ('nif', models.CharField(blank=True, db_column='nif', max_length=255, null=True)),
                ('pais_fiscal', models.CharField(blank=True, db_column='pais_fiscal', max_length=255, null=True)),
                ('digito_verificacao', models.CharField(blank=True, db_column='digito_verificacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='DSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, db_column='Período', max_length=255, null=True)),
                ('cod_disciplina', models.IntegerField(blank=True, db_column='Cód. disciplina', null=True)),
                ('disciplina', models.CharField(blank=True, db_column='Disciplina', max_length=255, null=True)),
                ('inst_discip', models.CharField(blank=True, db_column='Inst. discip.', max_length=255, null=True)),
                ('inst_disciplina', models.CharField(blank=True, db_column='Inst. disciplina', max_length=255, null=True)),
                ('depart_disciplina', models.CharField(blank=True, db_column='Depart. disciplina', max_length=255, null=True)),
                ('turma', models.CharField(blank=True, db_column='Turma', max_length=255, null=True)),
                ('codigo_curso', models.CharField(blank=True, db_column='Código curso', max_length=255, null=True)),
                ('curso', models.CharField(blank=True, db_column='Curso', max_length=255, null=True)),
                ('Cod_Docente', models.CharField(blank=True, db_column='Cód. Docente', max_length=255, null=True)),
                ('docente', models.CharField(blank=True, db_column='Docente', max_length=255, null=True)),
                ('func_docente', models.CharField(blank=True, db_column='Função docente', max_length=255, null=True)),
                ('inst_docente', models.CharField(blank=True, db_column='Inst. docente', max_length=255, null=True)),
                ('depart_docente', models.CharField(blank=True, db_column='Depart. docente', max_length=255, null=True)),
                ('horas_semanais', models.CharField(blank=True, db_column='Horas semanais', max_length=255, null=True)),
                ('horas_periodo', models.CharField(blank=True, db_column='Horas período', max_length=255, null=True)),
                ('factor', models.IntegerField(blank=True, db_column='Factor', null=True)),
                ('horas_servico', models.IntegerField(blank=True, db_column='Horas serviço', null=True)),
                ('data_inicio', models.CharField(blank=True, db_column='Data início', max_length=255, null=True)),
                ('data_fim', models.CharField(blank=True, db_column='Data fim', max_length=255, null=True)),
                ('nome_docente', models.CharField(blank=True, db_column='Nome Docente', max_length=255, null=True)),
                ('agrupamento', models.CharField(blank=True, db_column='Agrupamento', max_length=255, null=True)),
            ],
            options={
                'db_table': 'dsd',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('localizacao', models.CharField(blank=True, db_column='Localizacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Edificio',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, db_column='Sigla', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Instituicao',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.IntegerField(blank=True, db_column='T', null=True)),
                ('tp', models.IntegerField(blank=True, db_column='TP', null=True)),
                ('pl', models.IntegerField(blank=True, db_column='PL', null=True)),
                ('p', models.IntegerField(blank=True, db_column='P', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
            ],
            options={
                'db_table': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('inicio_data', models.DateField(blank=True, db_column='Inicio_Data', null=True)),
                ('fim_data', models.DateField(blank=True, db_column='Fim_Data', null=True)),
                ('nr_horas_service', models.IntegerField(blank=True, db_column='Nr_Horas_service', null=True)),
            ],
            options={
                'db_table': 'Semestre',
            },
        ),
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=255)),
            ],
            options={
                'db_table': 'TipoSala',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nturma', models.CharField(blank=True, db_column='NTurma', max_length=255, null=True)),
                ('horas_semanais', models.CharField(blank=True, db_column='Horas_semanais', max_length=255, null=True)),
                ('horas_periodo', models.CharField(blank=True, db_column='Horas_periodo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nsala', models.CharField(blank=True, db_column='NSala', max_length=255, null=True)),
                ('lotacao', models.IntegerField(blank=True, db_column='Lotacao', null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('anoletivo', models.ForeignKey(db_column='AnoLetivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.anoletivo')),
                ('edificioid', models.ForeignKey(db_column='EdificioID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.edificio')),
                ('tipo_sala', models.ManyToManyField(to='pedidos.tiposala')),
            ],
            options={
                'db_table': 'Sala',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nrpedido', models.IntegerField(blank=True, db_column='NrPedido', null=True)),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('dataalvo', models.DateField(blank=True, db_column='DataAlvo', null=True)),
                ('dataanalise', models.DateField(blank=True, db_column='DataAnalise', null=True)),
                ('datavalidacao', models.DateField(blank=True, db_column='DataValidacao', null=True)),
                ('datacriacao', models.DateTimeField(auto_now_add=True, db_column='DataCriacao', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('dataalteracao', models.DateTimeField(auto_now=True, db_column='DataAlteracao', null=True)),
                ('anoletivo', models.ForeignKey(db_column='AnoLetivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.anoletivo')),
                ('docente', models.ForeignKey(db_column='Docente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_users.docente')),
                ('funcionario', models.ForeignKey(db_column='Funcionario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_users.funcionario')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='LinhaSala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('detalhe', models.CharField(blank=True, db_column='Detalhe', max_length=255, null=True)),
                ('horainicio', models.TimeField(blank=True, db_column='HoraInicio', null=True)),
                ('horafim', models.TimeField(blank=True, db_column='HoraFim', null=True)),
                ('horainicioantigo', models.TimeField(blank=True, db_column='HoraInicioAntigo', null=True)),
                ('horafimantigo', models.TimeField(blank=True, db_column='HoraFimAntigo', null=True)),
                ('tipopedido', models.CharField(blank=True, db_column='TipoPedido', max_length=255, null=True)),
                ('categoriatemporal', models.CharField(blank=True, db_column='CategoriaTemporal', max_length=255, null=True)),
                ('pedidoID', models.ForeignKey(db_column='PedidoID', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('sala', models.ForeignKey(blank=True, db_column='Sala', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.sala')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaOutros',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('pedidoID', models.ForeignKey(db_column='PedidoID', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaHorario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipodepedido', models.CharField(blank=True, db_column='tipodepedido', max_length=255, null=True)),
                ('diadasemana', models.CharField(blank=True, db_column='diadasemana', max_length=255, null=True)),
                ('horainicio', models.TimeField(blank=True, db_column='HoraInicio', null=True)),
                ('horafim', models.TimeField(blank=True, db_column='HoraFim', null=True)),
                ('datainicio', models.DateField(blank=True, db_column='DataInicio', null=True)),
                ('datafim', models.DateField(blank=True, db_column='DataFim', null=True)),
                ('novadiadasemana', models.CharField(blank=True, db_column='novadiadasemana', max_length=255, null=True)),
                ('novahorainicio', models.TimeField(blank=True, db_column='novaHoraInicio', null=True)),
                ('novahorafim', models.TimeField(blank=True, db_column='novaHoraFim', null=True)),
                ('novadatainicio', models.DateField(blank=True, db_column='novaDataInicio', null=True)),
                ('novadatafim', models.DateField(blank=True, db_column='novaDataFim', null=True)),
                ('pedidoID', models.ForeignKey(db_column='PedidoID', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('pedidoID', models.ForeignKey(db_column='PedidoID', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('uc', models.ForeignKey(db_column='Disciplina', on_delete=django.db.models.deletion.CASCADE, to='pedidos.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='EdificioInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.edificio')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.instituicao')),
            ],
            options={
                'db_table': 'Edificio_Instituicao',
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='instituicao',
            field=models.ManyToManyField(related_name='edificios', through='pedidos.EdificioInstituicao', to='pedidos.instituicao'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestreid',
            field=models.ForeignKey(db_column='SemestreID', on_delete=django.db.models.deletion.CASCADE, to='pedidos.semestre'),
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('cursoid', models.OneToOneField(db_column='CursoID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pedidos.curso')),
                ('disciplinaid2', models.ForeignKey(db_column='DisciplinaID2', on_delete=django.db.models.deletion.CASCADE, to='pedidos.disciplina')),
            ],
            options={
                'db_table': 'Curso_Disciplina',
                'unique_together': {('cursoid', 'disciplinaid2')},
            },
        ),
    ]
